// app/api/send-email/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { Agent, setGlobalDispatcher } from 'undici';

// Force IPv4 for all outbound Node.js fetch requests in this process.
// This resolves ETIMEDOUT issues with Google APIs on dual-stack IPv6 networks.
setGlobalDispatcher(new Agent({
  connect: {
    family: 4
  }
}));

const GOOGLE_CLIENT_ID = '1051301645220-it8a07gtd3l98kpqd3u5pug6rmah2e3s.apps.googleusercontent.com';
const GOOGLE_CLIENT_SECRET = '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';
const GOOGLE_REFRESH_TOKEN = '1//0guvE98paTFsrCgYIARAAGBASNwF-L9IrN7RpLYoDDfTEDOx6lbpbIzxdnfH9oD_2EkFO6kskvoxyOYBnASL8J33VF8YC1JFfgko';
const SENDER_EMAIL = 'mailer@vesimplify.com';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { to, subject, bodyText, attachments } = body;

    // 1. Basic validation
    if (!to || typeof to !== 'string' || !to.includes('@')) {
      return NextResponse.json({ error: 'A valid recipient email address is required' }, { status: 400 });
    }

    if (!subject || typeof subject !== 'string') {
      return NextResponse.json({ error: 'Email subject is required' }, { status: 400 });
    }

    // 2. Fetch Google OAuth access token
    const tokenResponse = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: GOOGLE_CLIENT_ID,
        client_secret: GOOGLE_CLIENT_SECRET,
        refresh_token: GOOGLE_REFRESH_TOKEN,
        grant_type: 'refresh_token',
      }),
    });

    if (!tokenResponse.ok) {
      const errorText = await tokenResponse.text();
      console.error('[send-email] Token refresh failed:', errorText);
      return NextResponse.json({ error: `Failed to refresh OAuth token: ${errorText}` }, { status: 500 });
    }

    const tokenData = await tokenResponse.json();
    const accessToken = tokenData.access_token;

    // 3. Construct the MIME message
    const boundary = `----=_Part_${Date.now()}_${Math.random().toString(36).substring(2)}`;
    const mimeParts = [
      `MIME-Version: 1.0`,
      `From: ${SENDER_EMAIL}`,
      `To: ${to}`,
      `Subject: ${subject}`,
      `Content-Type: multipart/mixed; boundary="${boundary}"`,
      ``,
      `--${boundary}`,
      `Content-Type: text/plain; charset="utf-8"`,
      `Content-Transfer-Encoding: 7bit`,
      ``,
      bodyText || 'Please find the attached SQL scripts generated by QueryPulse.',
      ``,
    ];

    if (attachments && Array.isArray(attachments)) {
      for (const att of attachments) {
        if (!att.filename || !att.content) continue;
        mimeParts.push(`--${boundary}`);
        mimeParts.push(`Content-Type: text/plain; name="${att.filename}"`);
        mimeParts.push(`Content-Disposition: attachment; filename="${att.filename}"`);
        mimeParts.push(`Content-Transfer-Encoding: base64`);
        mimeParts.push(``);

        const base64Content = Buffer.from(att.content).toString('base64');
        // Chunk base64 content to 76 chars per line (standard MIME requirement)
        const chunkedBase64 = base64Content.match(/.{1,76}/g)?.join('\r\n') || base64Content;
        mimeParts.push(chunkedBase64);
        mimeParts.push(``);
      }
    }

    mimeParts.push(`--${boundary}--`);

    // Assemble raw MIME text
    const rawEmail = mimeParts.join('\r\n');
    
    // Convert to Gmail API-safe base64url encoding
    const base64url = Buffer.from(rawEmail)
      .toString('base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');

    // 4. Send email via Gmail API
    const gmailResponse = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        raw: base64url,
      }),
    });

    if (!gmailResponse.ok) {
      const errorText = await gmailResponse.text();
      console.error('[send-email] Gmail sending API failed:', errorText);
      return NextResponse.json({ error: `Gmail delivery failed: ${errorText}` }, { status: 500 });
    }

    const gmailData = await gmailResponse.json();
    return NextResponse.json({ success: true, messageId: gmailData.id });
  } catch (error: any) {
    console.error('[send-email] General error:', error);
    return NextResponse.json(
      { error: error.message || 'An unexpected error occurred while sending the email' },
      { status: 500 }
    );
  }
}
